version: '2'

services:
  orbs-network-node-1:
    image: orbs:export
    ports:
      - 8080:8080
    volumes:
      - ./logs/:/opt/orbs/logs
      - ./e2e-config/:/opt/orbs/config
    command: /opt/orbs/orbs-node --silent --config /opt/orbs/config/node1.json --log /opt/orbs/logs/node1.log
    networks:
      orbs-network:
        ipv4_address: 192.168.199.2

  orbs-network-node-2:
    image: orbs:export
    environment:
      LOG_PATH: /opt/orbs/logs/node2.log
    ports:
      - 8081:8080
    volumes:
      - ./logs/:/opt/orbs/logs
      - ./e2e-config/:/opt/orbs/config
    command: /opt/orbs/orbs-node --silent --config /opt/orbs/config/node2.json --log /opt/orbs/logs/node2.log
    networks:
      orbs-network:
        ipv4_address: 192.168.199.3

  orbs-network-node-3:
    image: orbs:export
    environment:
      LOG_PATH: /opt/orbs/logs/node3.log
    ports:
      - 8082:8080
    volumes:
      - ./logs/:/opt/orbs/logs
      - ./e2e-config/:/opt/orbs/config
    command: /opt/orbs/orbs-node --silent --config /opt/orbs/config/node3.json --log /opt/orbs/logs/node3.log
    networks:
      orbs-network:
        ipv4_address: 192.168.199.4

  orbs-e2e:
    image: orbs:e2e
    environment:
      API_ENDPOINT: http://orbs-network-node-3:8080/api/v1/
    command: sh -c "sleep 10 && ./e2e.test"
    networks:
      orbs-network:
        ipv4_address: 192.168.199.5

networks:
  orbs-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.199.0/24
