version: 2
jobs:
  tests:
    docker:
      - image: itamararjuan/golang_with_node_aws
    resource_class: large
    steps:
      - checkout
      - run: go get -u github.com/orbs-network/go-junit-report
      - run: ./test.sh
      - store_artifacts:
          path: _out
          destination: test-output
      - store_artifacts:
          path: _reports
          destination: test-results
      - store_test_results:
          path: _reports

  memory_leaks:
    docker:
      - image: circleci/golang:1.12.6
    resource_class: xlarge
    steps:
      - checkout
      - run: ./test.goroutine-leaks.sh
      - run: ./test.memory-leaks.sh

  flakiness:
    docker:
      - image: itamararjuan/golang_with_node_aws
    parallelism: 6
    resource_class: xlarge
    steps:
      - checkout
      - run: go get -u github.com/orbs-network/go-junit-report
      - run:
          command: ./test.flakiness.sh
          no_output_timeout: 25m
      - store_artifacts:
          path: _out
          destination: test-output
      - store_artifacts:
          path: _reports
          destination: test-results
      - store_test_results:
          path: _reports

  nightly:
    docker:
      - image: circleci/golang:1.12.6
    parallelism: 6
    resource_class: xlarge
    steps:
      - checkout
      - run:
          command: ./.circleci/nightly.sh
          no_output_timeout: 300m
      - store_artifacts:
          path: _out
          destination: test-output
      - store_artifacts:
          path: _reports
          destination: test-results
      - store_test_results:
          path: _reports

  e2e:
    machine: 
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: ./.circleci/install-go.sh
      - run: ./docker/build/build.sh
      # Update docker-compose
      - run: sudo bash -c "rm -rf /usr/local/bin/docker-compose && pip install docker-compose==1.23.2"
      - run:
          command: ./docker/test/test.sh
          environment:
            CONSENSUSALGO: benchmark
      # Logs here belong to root
      - run: sudo rm -rf _logs
      - run:
          command: ./docker/test/test.sh
          environment:
            CONSENSUSALGO: leanhelix
      - run: ./.circleci/release-internal.sh
      - store_artifacts:
          path: _logs

  success:
    machine: true
    steps:
      - run: echo 'Success'

  deploy_testnet:
    docker:
      - image: circleci/node:11.2.0
    steps:
      - checkout
      - run: ./.circleci/set-aws-credentials.sh
      - run: ./.circleci/deploy-testnet.sh

  e2e_testnet_benchmark:
    docker:
      - image: circleci/golang:1.12.6
    steps:
      - checkout
      - run: sleep 300
      - run: ./.circleci/e2e-testnet.sh 42

  e2e_testnet_leanhelix:
    docker:
    - image: circleci/golang:1.12.6
    steps:
    - checkout
    - run: sleep 300
    - run: ./.circleci/e2e-testnet.sh 2013

  deploy_new_chain_pr_only:
    docker:
    - image: itamararjuan/golang_with_node_aws
    environment:
      BOOTSTRAP_URL: "https://boyar-testnet-bootstrap.s3-us-west-2.amazonaws.com/boyar/config.json"
      BOOTSTRAP_S3_URI: "s3://boyar-testnet-bootstrap/boyar/config.json"
      TESTNET_NODE_IP: "35.161.123.97"
      TESTNET_IGNORE_IPS: ""
    steps:
      - checkout
      - run: ./.circleci/chain_on_pr.sh

  release:
    machine: true
    steps:
    - checkout
    - run: ./.circleci/release.sh

workflows:
  version: 2
  build:
    jobs:
      - tests:
          filters:
            tags:
              only: /^v.*/

      - deploy_new_chain_pr_only:
          requires:
            - e2e
            - tests
      - memory_leaks:
          requires:
            - tests
      - e2e:
          filters:
            tags:
              only: /^v.*/
      - flakiness
      - success:
          requires:
            - tests
            - e2e
      - deploy_testnet:
          requires:
            - e2e
          filters:
            branches:
              only:
                - master
      # - e2e_testnet_benchmark:
      #     requires:
      #       - deploy_testnet
      # - e2e_testnet_leanhelix:
      #     requires:
      #       - deploy_testnet
      - release:
          requires:
            - tests
            - e2e
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master

  nightly:
    triggers:
      - schedule:
          cron: "0 23 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - nightly


