version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: ./git-submodule-checkout.sh
      - run: ./docker/build/build.sh
      - run: ./docker/test/test.sh
      - run: sudo chown -R circleci:circleci _logs && ./.circleci/upload-node-metrics.sh
      - run: docker tag orbs:export $DOCKER_IMAGE:$(./docker/tag.sh)
      - run: docker tag orbs:export $DOCKER_IMAGE:$(./docker/hash.sh)
      - run: $(aws ecr get-login --no-include-email --region us-west-2)
      - run: docker push $DOCKER_IMAGE
      - store_artifacts:
          path: _logs
      - store_artifacts:
          path: _out
      - store_test_results:
          path: _out


  flakiness:
    machine: true
    steps:
      - checkout
      - run: ./git-submodule-checkout.sh
      - run: ./docker/build/build.flakiness.sh
      - run:
          # remove logs if the test was successful for quicker feedback loop
          command: ./docker/test/test.flakiness.sh #&& sudo find _logs/acceptance -type f -delete
          no_output_timeout: 25m
      - run:
          command: sudo chown -R circleci:circleci _logs && ./.circleci/upload-node-metrics.sh && ./.circleci/archive-logs.sh
          no_output_timeout: 25m
      - store_artifacts:
          path: _logs

  notify_github_about_dashboard:
    machine: true
    steps:
      - checkout
      - run: python ./.circleci/post-dashboard-link.py

  success:
    machine: true
    steps:
      - run: echo 'Success'

  deploy_testnet:
    machine: true
    steps:
      - checkout
      - run: $(aws ecr get-login --no-include-email --region us-west-2)
      - run: docker pull $DOCKER_IMAGE:master
      - run: ./.circleci/set-aws-credentials.sh
      - run: ./.circleci/deploy-testnet.sh

  e2e_testnet:
    machine: true
    steps:
      - checkout
      - run: ./git-submodule-checkout.sh
      - run: ./docker/build/build.sh
      - run: ./.circleci/e2e-testnet.sh 42
      - run: ./.circleci/e2e-testnet.sh 2013

  release_gamma:
    machine: true
    steps:
      - checkout
      - run: ./git-submodule-checkout.sh
      - run: ./docker/build/build.sh
      - run: ./.circleci/release-gamma.sh

  autonomous_swap:
    machine: true
    steps:
      - checkout
      - run: ./git-submodule-checkout.sh
      - run: ./docker/build/build.sh
      - run: docker tag orbs:gamma-server orbsnetwork/gamma:experimental
      - run: cd vendor/github.com/orbs-network/orbs-ethereum-contracts/ && .circleci/main.sh

workflows:
  version: 2
  build:
    jobs:
      - build
      - flakiness
      - notify_github_about_dashboard
      - autonomous_swap
      - success:
          requires:
            - build
            - flakiness
      - deploy_testnet:
          requires:
            - success
          filters:
            branches:
              only:
                - master
      - e2e_testnet:
          requires:
            - deploy_testnet
          filters:
            branches:
              only:
                - master
      - release_gamma:
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - master
